/**
 * Token generators — flattens the token objects into CSS custom properties
 * and a Tailwind-compatible theme config.
 */

import {
  typeScale,
  spacing,
  radius,
  shadow,
  transition,
  zIndex,
  semanticDark,
  semanticLight,
} from './tokens.js';

type TokenMap = Record<string, string>;

function flattenObject(obj: object, prefix = ''): TokenMap {
  const result: TokenMap = {};
  for (const [key, value] of Object.entries(obj)) {
    const varName = prefix ? `${prefix}-${key}` : key;
    if (typeof value === 'object' && value !== null) {
      Object.assign(result, flattenObject(value as object, varName));
    } else {
      result[varName] = String(value);
    }
  }
  return result;
}

function toCustomProps(map: TokenMap, indent = '  '): string {
  return Object.entries(map)
    .map(([k, v]) => `${indent}--${k}: ${v};`)
    .join('\n');
}

/** Returns the full tokens.css content. */
export function generateTokensCSS(): string {
  const darkColors = flattenObject(semanticDark.color, 'color');
  const lightColors = flattenObject(semanticLight.color, 'color');
  const fonts = flattenObject(typeScale.fontFamily, 'font');
  const fontSizes = flattenObject(typeScale.fontSize, 'font-size');
  const fontWeights = flattenObject(typeScale.fontWeight, 'font-weight');
  const lineHeights = flattenObject(typeScale.lineHeight, 'line-height');
  const letterSpacings = flattenObject(typeScale.letterSpacing, 'letter-spacing');
  const spacingVars = Object.fromEntries(
    Object.entries(spacing).map(([k, v]) => [`spacing-${k}`, v]),
  );
  const radiusVars = Object.fromEntries(
    Object.entries(radius).map(([k, v]) => [`radius-${k}`, v]),
  );
  const shadowVars = Object.fromEntries(
    Object.entries(shadow).map(([k, v]) => [`shadow-${k}`, v]),
  );
  const durationVars = flattenObject(transition.duration, 'duration');
  const easingVars = flattenObject(transition.easing, 'easing');
  const zVars = Object.fromEntries(
    Object.entries(zIndex).map(([k, v]) => [`z-${k}`, v]),
  );

  const rootVars = {
    ...darkColors,
    ...fonts,
    ...fontSizes,
    ...fontWeights,
    ...lineHeights,
    ...letterSpacings,
    ...spacingVars,
    ...radiusVars,
    ...shadowVars,
    ...durationVars,
    ...easingVars,
    ...zVars,
  };

  return [
    '/* Generated by packages/design-system/scripts/build-tokens.ts — do not edit */',
    '',
    ':root {',
    toCustomProps(rootVars),
    '}',
    '',
    '[data-theme="light"] {',
    toCustomProps(lightColors),
    '}',
    '',
  ].join('\n');
}

/** Returns a Tailwind 3 preset config object (references CSS vars at runtime). */
export function generateTailwindPreset(): object {
  const colorGroup = (prefix: string, keys: string[]) =>
    Object.fromEntries(keys.map((k) => [k, `var(--color-${prefix}-${k})`]));

  return {
    theme: {
      extend: {
        colors: {
          bg: colorGroup('bg', ['base', 'surface', 'elevated', 'overlay', 'inverted']),
          text: colorGroup('text', ['primary', 'secondary', 'muted', 'disabled', 'inverted', 'brand']),
          brand: {
            DEFAULT: 'var(--color-brand-default)',
            hover: 'var(--color-brand-hover)',
            active: 'var(--color-brand-active)',
            subtle: 'var(--color-brand-subtle)',
            border: 'var(--color-brand-border)',
          },
          border: colorGroup('border', ['default', 'strong', 'subtle', 'brand']),
          status: {
            success: 'var(--color-status-success)',
            'success-subtle': 'var(--color-status-success-subtle)',
            error: 'var(--color-status-error)',
            'error-subtle': 'var(--color-status-error-subtle)',
            warning: 'var(--color-status-warning)',
            'warning-subtle': 'var(--color-status-warning-subtle)',
            info: 'var(--color-status-info)',
            'info-subtle': 'var(--color-status-info-subtle)',
          },
        },
        fontFamily: {
          sans: ['var(--font-sans)'],
          mono: ['var(--font-mono)'],
        },
        fontSize: Object.fromEntries(
          Object.keys(typeScale.fontSize).map((k) => [k, `var(--font-size-${k})`]),
        ),
        fontWeight: Object.fromEntries(
          Object.keys(typeScale.fontWeight).map((k) => [k, `var(--font-weight-${k})`]),
        ),
        lineHeight: Object.fromEntries(
          Object.keys(typeScale.lineHeight).map((k) => [k, `var(--line-height-${k})`]),
        ),
        letterSpacing: Object.fromEntries(
          Object.keys(typeScale.letterSpacing).map((k) => [k, `var(--letter-spacing-${k})`]),
        ),
        spacing: Object.fromEntries(
          Object.keys(spacing).map((k) => [k.replace('-', '.'), `var(--spacing-${k})`]),
        ),
        borderRadius: Object.fromEntries(
          Object.keys(radius).map((k) => [k, `var(--radius-${k})`]),
        ),
        boxShadow: Object.fromEntries(
          Object.keys(shadow).map((k) => [k, `var(--shadow-${k})`]),
        ),
        transitionDuration: Object.fromEntries(
          Object.keys(transition.duration).map((k) => [k, `var(--duration-${k})`]),
        ),
        transitionTimingFunction: Object.fromEntries(
          Object.keys(transition.easing).map((k) => [k, `var(--easing-${k})`]),
        ),
        zIndex: Object.fromEntries(
          Object.keys(zIndex).map((k) => [k, `var(--z-${k})`]),
        ),
      },
    },
  };
}
