// Auto-generated by tauri-specta — do not edit manually.
// Run `cargo run --bin generate-bindings` to regenerate.

import { invoke } from '@tauri-apps/api/core'

export const commands = {
  /**
   * Health-check / smoke-test — useful for integration tests.
   */
  async ping(message: string): Promise<string> {
    return await invoke<string>('ping', { message })
  },

  /**
   * Returns the Mantle version string.
   */
  async getVersion(): Promise<string> {
    return await invoke<string>('get_version')
  },
}
