#[cfg(target_os = "linux")]
pub mod audio;
#[cfg(target_os = "linux")]
pub mod brightness;
pub mod metrics;
#[cfg(target_os = "linux")]
pub mod mpris;
#[cfg(target_os = "linux")]
pub mod network;
pub mod power;
#[cfg(target_os = "linux")]
pub mod power_supply;
pub mod widget_config;
