mod bridge;
#[cfg(target_os = "linux")]
mod compositor;
mod config;
pub mod launcher;
mod layer_shell;
#[cfg(target_os = "linux")]
mod notifications;
mod registry;
mod services;
mod styling;
#[cfg(target_os = "linux")]
mod tray;

use styling::StylingLoader;

use config::{loader, watcher, ConfigState};
use tauri::Emitter;

const BINDINGS_HEADER: &str = "// Auto-generated by tauri-specta — do not edit manually.\n\
     // Run `cargo run --bin generate-bindings` to regenerate.\n\n";

fn typescript_exporter() -> specta_typescript::Typescript {
    specta_typescript::Typescript::default().header(BINDINGS_HEADER)
}

/// Export TypeScript bindings from the typed command bridge.
pub fn export_bindings() {
    bridge::build_commands()
        .export(typescript_exporter(), "../src/lib/bridge/bindings.ts")
        .expect("Failed to export TypeScript bindings");
}

#[specta::specta]
#[tauri::command]
async fn load_styling(
    state: tauri::State<'_, StylingLoader>,
    tool: String,
    version: String,
    input: String,
) -> Result<styling::LoadResult, String> {
    state
        .load(&tool, &version, &input)
        .await
        .map_err(|e| e.to_string())
}

/// Replace any character not allowed in a Tauri window label with `-`.
/// Labels permit ASCII alphanumerics plus `-` and `_`.
#[cfg(target_os = "linux")]
fn sanitize_label(s: &str) -> String {
    s.chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() || c == '-' || c == '_' {
                c
            } else {
                '-'
            }
        })
        .collect()
}

/// Spawn one layer-shell bar window per connected output.
///
/// Each bar is a runtime-created webview labeled `bar-<output>`, pinned to its
/// `gdk::Monitor`, and given the standard top-bar layer-shell config.  Labels
/// are deduped so identical monitor models don't collide.  Returns the number
/// of bars successfully shown; `0` means the caller should fall back to the
/// single static `bar` window.
///
/// Note: GTK3 exposes only the monitor model, not the compositor connector, so
/// `<output>` is the model (or `output-<index>`).  Per-output config still
/// resolves via `OutputConfig::resolve`, which falls back to the `*` wildcard
/// for unmatched names.
#[cfg(target_os = "linux")]
fn spawn_output_bars<M: tauri::Manager<tauri::Wry>>(manager: &M) -> usize {
    use tauri::{WebviewUrl, WebviewWindowBuilder};

    let monitors = layer_shell::LayerShellManager::monitor_handles();
    let mut used = std::collections::HashSet::new();
    let mut shown = 0;

    for (i, (output, monitor)) in monitors.iter().enumerate() {
        // Derive a unique, label-safe suffix for this output.
        let mut suffix = sanitize_label(output);
        if suffix.is_empty() {
            suffix = format!("output-{i}");
        }
        if !used.insert(suffix.clone()) {
            suffix = format!("{suffix}-{i}");
            used.insert(suffix.clone());
        }
        let label = format!("bar-{suffix}");

        let win = match WebviewWindowBuilder::new(
            manager,
            label.clone(),
            WebviewUrl::App("index.html".into()),
        )
        .visible(false)
        .decorations(false)
        .transparent(true)
        .resizable(false)
        .skip_taskbar(true)
        .inner_size(1920.0, 36.0)
        .build()
        {
            Ok(w) => w,
            Err(e) => {
                log::error!("bar window for output '{output}' ({label}) failed to build: {e}");
                continue;
            }
        };

        let gtk_win = match win.gtk_window() {
            Ok(g) => g,
            Err(e) => {
                log::error!("GTK window for '{label}' unavailable: {e}");
                continue;
            }
        };
        let config = layer_shell::SurfaceConfig::top_bar(36, format!("mantle-{label}"));
        layer_shell::LayerShellManager::apply_to_window(&gtk_win, &config, Some(monitor));
        if let Err(e) = win.show() {
            log::error!("showing bar '{label}' failed: {e}");
            continue;
        }
        shown += 1;
    }

    shown
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    env_logger::Builder::from_env(env_logger::Env::default().default_filter_or("info")).init();

    // Load config from XDG path (writes defaults on first run).
    let (initial_config, config_path) = match loader::load() {
        Ok(pair) => pair,
        Err(e) => {
            log::error!("fatal: cannot load config: {e:#}");
            std::process::exit(1);
        }
    };

    // File-watch channel: receives updated Config on each file save.
    let config_rx = watcher::spawn(config_path, initial_config.clone());
    let config_state = ConfigState::new(initial_config, config_rx.clone());

    let commands = bridge::build_commands();

    // In debug builds, regenerate the TS bindings so the committed copy stays current.
    #[cfg(debug_assertions)]
    commands
        .export(typescript_exporter(), "../src/lib/bridge/bindings.ts")
        .expect("Failed to export TypeScript bindings");

    let invoke_handler = commands.invoke_handler();

    let builder = tauri::Builder::default()
        .plugin(tauri_plugin_shell::init())
        .invoke_handler(invoke_handler)
        .manage(config_state.clone())
        .manage(StylingLoader::new());

    // Install all self-registered plugins (services from other streams).
    // The launcher plugin is self-registered in launcher::plugin via inventory::submit!
    let builder = registry::setup(builder);

    builder
        .setup(move |app| {
            use tauri::Manager;
            // Keep the in-memory Config in sync with the file watcher.
            config_state.start_sync_loop();

            // Bridge watcher → frontend: emit "config-changed" on each reload.
            {
                let app_handle = app.handle().clone();
                let mut rx = config_rx.clone();
                tauri::async_runtime::spawn(async move {
                    while rx.changed().await.is_ok() {
                        let new_cfg = rx.borrow().clone();
                        app_handle.emit("config-changed", &new_cfg).ok();
                    }
                });
            }

            // Path A: apply layer-shell before each bar window is shown.
            #[cfg(target_os = "linux")]
            {
                // One layer-shell bar per connected output, each pinned to its
                // monitor and labeled `bar-<output>` (resolved by the App.tsx
                // surface router + BarShell::outputFromLabel).  Falls back to the
                // static "bar" window from tauri.conf.json if no monitors could
                // be enumerated.
                if spawn_output_bars(app.handle()) == 0 {
                    let win = app
                        .get_webview_window("bar")
                        .expect("bar window defined in tauri.conf.json");
                    let gtk_win = win.gtk_window().expect("failed to get GTK window for bar");
                    let bar_config = layer_shell::SurfaceConfig::top_bar(36, "mantle-bar");
                    layer_shell::LayerShellManager::apply_to_window(&gtk_win, &bar_config, None);
                    win.show().expect("failed to show bar window");
                }

                if let Some(launcher_win) = app.get_webview_window("launcher") {
                    launcher::setup_surface(&launcher_win)
                        .expect("Failed to apply layer shell to launcher window");
                }

                // Widgets overlay: Top layer, top-right anchored, no exclusive zone,
                // on-demand keyboard (needed for any user interaction inside widgets).
                if let Some(widgets_win) = app.get_webview_window("widgets") {
                    let gtk_win = widgets_win
                        .gtk_window()
                        .expect("failed to get GTK window for widgets");
                    let widgets_config = layer_shell::SurfaceConfig {
                        layer: layer_shell::Layer::Top,
                        anchors: [true, true, false, false], // top + right anchored
                        exclusive_zone: layer_shell::ExclusiveZone::None,
                        margins: (0, 0, 0, 0),
                        keyboard_mode: layer_shell::KeyboardMode::OnDemand,
                        namespace: "mantle-widgets".to_string(),
                    };
                    layer_shell::LayerShellManager::apply_to_window(
                        &gtk_win,
                        &widgets_config,
                        None,
                    );
                    widgets_win.show().expect("failed to show widgets window");
                }

                // Subscribe to compositor events and relay them as Tauri events.
                compositor::spawn_event_relay(app.handle().clone());
            }

            // On non-Linux (dev/CI), show the window normally.
            #[cfg(not(target_os = "linux"))]
            {
                if let Some(win) = app.get_webview_window("bar") {
                    let _ = win.show();
                }
                if let Some(win) = app.get_webview_window("widgets") {
                    let _ = win.show();
                }
            }

            // Global shortcut: Super+Space toggles the app launcher, which
            // starts hidden (see launcher::setup_surface).
            //
            // NOTE: native Wayland compositors (sway/Hyprland) own global key
            // bindings, so this app-registered shortcut only fires under
            // X11/XWayland.  On Wayland, bind a key in the compositor config to
            // a command that toggles the launcher instead.
            #[cfg(desktop)]
            {
                use tauri_plugin_global_shortcut::{
                    Code, GlobalShortcutExt, Modifiers, Shortcut, ShortcutState,
                };

                let plugin = tauri_plugin_global_shortcut::Builder::new()
                    .with_handler(|app, _shortcut, event| {
                        // Only Super+Space is registered, so any press toggles.
                        if event.state() == ShortcutState::Pressed {
                            launcher::toggle_launcher(app);
                        }
                    })
                    .build();

                if let Err(e) = app.handle().plugin(plugin) {
                    log::warn!("global-shortcut plugin unavailable: {e}");
                } else if let Err(e) = app
                    .global_shortcut()
                    .register(Shortcut::new(Some(Modifiers::SUPER), Code::Space))
                {
                    log::warn!("could not bind launcher shortcut (Super+Space): {e}");
                }
            }

            Ok(())
        })
        .run(tauri::generate_context!())
        .expect("error while running Mantle");
}

#[cfg(test)]
mod tests {
    /// CI gate: verifies the bridge command builder compiles and is
    /// structurally valid without panicking.  Does NOT write bindings.ts so
    /// that `git diff --exit-code -- 'src/lib/bridge/'` always passes (the
    /// diff only catches drift when a developer manually runs generate-bindings
    /// and fails to commit the result).
    ///
    /// To update bindings.ts after changing commands:
    ///   cargo run --bin generate-bindings  (from src-tauri/)
    #[test]
    fn export_bindings() {
        let _ = crate::bridge::build_commands();
    }
}
