mod bridge;
mod layer_shell;
pub mod launcher;
#[cfg(target_os = "linux")]
mod notifications;
mod registry;

const BINDINGS_HEADER: &str = "// Auto-generated by tauri-specta — do not edit manually.\n\
     // Run `cargo run --bin generate-bindings` to regenerate.\n\n";

fn typescript_exporter() -> specta_typescript::Typescript {
    specta_typescript::Typescript::default().header(BINDINGS_HEADER)
}

/// Export TypeScript bindings from the typed command bridge.
///
/// Called by the `generate-bindings` binary in CI to detect staleness.
pub fn export_bindings() {
    bridge::build_commands()
        .export(typescript_exporter(), "../src/lib/bridge/bindings.ts")
        .expect("Failed to export TypeScript bindings");
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    let commands = bridge::build_commands();

    // Generate TypeScript bindings in debug builds so the file stays current
    // during development. The CI staleness check diffs against the committed copy.
    #[cfg(debug_assertions)]
    commands
        .export(typescript_exporter(), "../src/lib/bridge/bindings.ts")
        .expect("Failed to export TypeScript bindings");

    let invoke_handler = commands.invoke_handler();

    let builder = tauri::Builder::default().invoke_handler(invoke_handler);

    // Install all self-registered plugins (services from other streams).
    // The launcher plugin is self-registered in launcher::plugin via inventory::submit!
    let builder = registry::setup(builder);

    builder
        .setup(|app| {
            use tauri::Manager;

            #[cfg(target_os = "linux")]
            {
                let win = app
                    .get_webview_window("bar")
                    .expect("bar window defined in tauri.conf.json");

                layer_shell::LayerShellManager::new()
                    .apply(&win, &layer_shell::SurfaceConfig::default_bar())
                    .expect("Failed to apply layer shell to bar window");

                if let Some(launcher_win) = app.get_webview_window("launcher") {
                    launcher::setup_surface(&launcher_win)
                        .expect("Failed to apply layer shell to launcher window");
                }
            }

            // On non-Linux, show the window normally so dev/CI still works.
            #[cfg(not(target_os = "linux"))]
            {
                if let Some(win) = app.get_webview_window("bar") {
                    let _ = win.show();
                }
            }

            Ok(())
        })
        .run(tauri::generate_context!())
        .expect("error while running Mantle");
}

#[cfg(test)]
mod tests {
    /// CI gate: verifies the bridge command builder compiles and is
    /// structurally valid without panicking.  Does NOT write bindings.ts so
    /// that `git diff --exit-code -- 'src/lib/bridge/'` always passes (the
    /// diff only catches drift when a developer manually runs generate-bindings
    /// and fails to commit the result).
    ///
    /// To update bindings.ts after changing commands:
    ///   cargo run --bin generate-bindings  (from src-tauri/)
    #[test]
    fn export_bindings() {
        let _ = crate::bridge::build_commands();
    }
}
